nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_credentials: false
            origin_regex: false
            allow_origin: [ '*' ]
            allow_headers: [ 'Origin','Accept','Content-Type','Authorization' ]
            allow_methods: [ 'POST','GET','DELETE','PUT','OPTIONS' ]
            max_age: 3600
        '^/':
            allow_credentials: false
            origin_regex: false
            allow_origin: [ '*' ]
            allow_headers: [ 'Origin','Accept','Content-Type' ]
            allow_methods: [ 'POST','GET','DELETE','PUT','OPTIONS' ]
            max_age: 3600
